# Generated by Django 5.1.4 on 2025-02-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodNutrition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FoodName", models.CharField(max_length=100)),
                ("Calorie", models.IntegerField()),
                ("Protein", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Fat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Sugar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VA", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VC", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VB1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VB2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Ca", models.IntegerField()),
                ("Fe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Zn", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Water", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cellulose", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Carotene", models.IntegerField()),
                ("Retinol", models.IntegerField()),
                ("VPP", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VE", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cholesterol", models.IntegerField()),
                ("K", models.IntegerField()),
                ("Na", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Mg", models.IntegerField()),
                ("Mn", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cu", models.DecimalField(decimal_places=2, max_digits=10)),
                ("P", models.IntegerField()),
                ("Se", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="FoodNutritionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FoodName", models.CharField(max_length=100)),
                ("Calorie", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Protein", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Fat", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Sugar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VA", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VC", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VB1", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VB2", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Ca", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Fe", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Zn", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Water", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cellulose", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Carotene", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Retinol", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VPP", models.DecimalField(decimal_places=2, max_digits=10)),
                ("VE", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cholesterol", models.DecimalField(decimal_places=2, max_digits=10)),
                ("K", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Na", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Mg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Mn", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Cu", models.DecimalField(decimal_places=2, max_digits=10)),
                ("P", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Se", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="NutritionDisease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DiseaseName", models.CharField(max_length=100)),
                ("VC", models.IntegerField()),
                ("VE", models.IntegerField()),
                ("VPP", models.IntegerField()),
                ("Cellulose", models.IntegerField()),
                ("Carotene", models.IntegerField()),
                ("Zn", models.IntegerField()),
                ("Se", models.IntegerField()),
                ("K", models.IntegerField()),
                ("Ca", models.IntegerField()),
                ("Mg", models.IntegerField()),
                ("Fe", models.IntegerField()),
                ("VB1", models.IntegerField()),
                ("VB2", models.IntegerField()),
            ],
        ),
    ]
